[package]
name = "ps4000lib"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-common = "0.3.1"
pico-sys = "0.0.1"
pico-sys-dynamic = "0.3.1"
